context = {
    'stylesheet': 'css/kult.css',
    'site_title': 'KULT - Codex Umbrae',
    'title': 'KULT',
    'subtitle': "Divinity Lost",
    'welcome': 'Beyond the veil of reality lies the truth of our prison. '
               'The illusion fractures. The metropolis bleeds.',
    'quote': '"We are but fragments of forgotten gods, wandering the labyrinth of lies."',
    'campaign_subtitle': 'Chronicles beyond sanity',
    'sessions_subtitle': 'Descents into the truth',
    'lore_subtitle': 'Forbidden knowledge',
    'characters_subtitle': 'Prisoners of the metropolis',
    'media_subtitle': 'Visions of the broken world',
    'search_subtitle': 'Seek what should not be found',
    'site_title_campaign': 'Kult - Kampagnen',
    'site_title_sessions': 'Kult - Sessions',
    'site_title_lore': 'Kult - Lore',
    'site_title_characters': 'Kult - Charaktere',
    'site_title_media': 'Kult - Medien',
    'site_title_search': 'Kult - Suche',
    'system_home': 'Kult Home',
    'url_home': 'kult_home',
    'url_campaign': 'kult_campaign',
    'url_sessions': 'kult_sessions',
    'url_lore': 'kult_lore',
    'url_characters': 'kult_characters',
    'url_media': 'kult_media',
    'url_search': 'kult_search',
}