context = {
    'stylesheet': 'css/daggerheart.css',
    'campaign_cards': 'daggerheart/campaign_cards.html',
    'characters': 'daggerheart/charaktere.html',
    'campaign': 'daggerheart/kampagnen.html',
    'lore': 'daggerheart/lore.html',
    'sessions': 'daggerheart/sessions.html',
    'site_title': 'Daggerheart',
    'title': 'Daggerheart',
    'subtitle': "Wo Hoffnung und Angst aufeinandertreffen",
    'welcome': 'In einer Welt voller Magie und Gefahren stellen sich Helden unmöglichen Herausforderungen.'
               ' Jeder Würfelwurf bringt sowohl Triumph als auch Leid mit sich.',
    'quote': [
        '"Hoffnung ist der Dolch, Angst ist das Herz."',
        '"Hoffnung ist die Klinge, die wir gemeinsam schmieden, wenn die Angst uns allein lassen würde."',
        '"Trage die Last eines Freundes, denn kein Held geht allein."',
        '"Wir sind die Summe unserer Verbindungen zueinander."',
        '"Licht und Schatten, die in derselben Seele tanzen."',
        '"Jede Narbe erzählt zwei Geschichten: die der Wunde, die sie verursacht hat, '
        'und die der Kraft, die sie geheilt hat"',
        '"Vertrauen ist nicht die Abwesenheit von Angst, '
        'sondern trotz dieser Angst nach einer anderen Hand zu greifen"',
        '"Die Dunkelheit lässt unser gemeinsames Licht nur noch heller leuchten"',
        '"Wenn die Würfel dich im Stich lassen, fangen deine Gefährten dich auf"',
    ],
    'campaign_subtitle': 'Epische Abenteuergeschichten',
    'sessions_subtitle': 'Chroniken der Helden',
    'lore_subtitle': 'Legenden und Mythen',
    'characters_subtitle': 'Champions des Reiches',
    'site_title_campaign': 'Daggerheart - Kampagnen',
    'site_title_sessions': 'Daggerheart - Sessions',
    'site_title_lore': 'Daggerheart - Lore',
    'site_title_characters': 'Daggerheart - Charaktere',
    'system_home': 'Daggerheart Home',
    'url_home': 'daggerheart_home',
    'url_campaign': 'daggerheart_campaign',
    'url_sessions': 'daggerheart_sessions',
    'url_lore': 'daggerheart_lore',
    'url_characters': 'daggerheart_characters',
}
