context = {
    'stylesheet': 'css/daggerheart.css',
    'campaign_cards': 'daggerheart/campaign_cards.html',
    'characters': 'daggerheart/charaktere.html',
    'campaign': 'daggerheart/kampagnen.html',
    'lore': 'daggerheart/lore.html',
    'media': 'daggerheart/medien.html',
    'sessions': 'daggerheart/sessions.html',
    'search': 'daggerheart/search.html',
    'site_title': 'Daggerheart - Codex Umbrae',
    'title': 'Daggerheart',
    'subtitle': "Where Hope and Fear Collide",
    'welcome': 'In a world of magic and peril, heroes rise to face impossible odds. '
               'Every roll of the dice brings both triumph and tribulation.',
    'quote': '"Hope is the dagger, fear is the heart."',
    'campaign_subtitle': 'Epic tales of adventure',
    'sessions_subtitle': 'Chronicles of heroic deeds',
    'lore_subtitle': 'Legends and mythology',
    'characters_subtitle': 'Champions of the realm',
    'media_subtitle': 'Visions of wonder',
    'search_subtitle': 'Quest through the archives',
    'site_title_campaign': 'Daggerheart - Kampagnen',
    'site_title_sessions': 'Daggerheart - Sessions',
    'site_title_lore': 'Daggerheart - Lore',
    'site_title_characters': 'Daggerheart - Charaktere',
    'site_title_media': 'Daggerheart - Medien',
    'site_title_search': 'Daggerheart - Suche',
    'system_home': 'Daggerheart Home',
    'url_home': 'daggerheart_home',
    'url_campaign': 'daggerheart_campaign',
    'url_sessions': 'daggerheart_sessions',
    'url_lore': 'daggerheart_lore',
    'url_characters': 'daggerheart_characters',
    'url_media': 'daggerheart_media',
    'url_search': 'daggerheart_search',
}
