context = {
    'stylesheet': 'css/daggerheart.css',
    'campaign_cards': 'daggerheart/campaign_cards.html',
    'characters': 'daggerheart/charaktere.html',
    'campaign': 'daggerheart/kampagnen.html',
    'lore': 'daggerheart/lore.html',
    'sessions': 'daggerheart/sessions.html',
    'site_title': 'Daggerheart',
    'title': 'Daggerheart',
    'subtitle': "Where Hope and Fear Collide",
    'welcome': 'In a world of magic and peril, heroes rise to face impossible odds. '
               'Every roll of the dice brings both triumph and tribulation.',
    'quote': [
        '"Hope is the dagger, fear is the heart."',
        '"Hope is the blade we forge together, when fear would have us stand alone"',
        '"Carry another burden, for no hero walks alone"',
        '"We are the sum of our connections"',
        '"Light and Shadow, dancing in the same soul"',
        '"Every scar tells two stories, the wound that made it and the strength to heal it"',
        '"Trust is not the absence of fear, it is reaching for another hand despite it"',
        '"The darkness only makes our shared light burn brighter"',
        '"When the dice betray you, your companions will catch you"',
    ],
    'campaign_subtitle': 'Epic tales of adventure',
    'sessions_subtitle': 'Chronicles of heroic deeds',
    'lore_subtitle': 'Legends and mythology',
    'characters_subtitle': 'Champions of the realm',
    'media_subtitle': 'Visions of wonder',
    'search_subtitle': 'Quest through the archives',
    'site_title_campaign': 'Daggerheart - Kampagnen',
    'site_title_sessions': 'Daggerheart - Sessions',
    'site_title_lore': 'Daggerheart - Lore',
    'site_title_characters': 'Daggerheart - Charaktere',
    'site_title_media': 'Daggerheart - Medien',
    'site_title_search': 'Daggerheart - Suche',
    'system_home': 'Daggerheart Home',
    'url_home': 'daggerheart_home',
    'url_campaign': 'daggerheart_campaign',
    'url_sessions': 'daggerheart_sessions',
    'url_lore': 'daggerheart_lore',
    'url_characters': 'daggerheart_characters',
    'url_media': 'daggerheart_media',
    'url_search': 'daggerheart_search',
}
