# Generated by Django 5.2.7 on 2026-01-18 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the system', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly abbreviation of the name', unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the system')),
            ],
            options={
                'verbose_name': 'System',
                'verbose_name_plural': 'Systems',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WikiEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Entry title', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly abbreviation of the title', max_length=200)),
                ('entry_type', models.CharField(choices=[('location', 'Ort'), ('npc', 'NPC'), ('player_character', 'Spielercharakter'), ('item', 'Gegenstand'), ('faction', 'Fraktion'), ('event', 'Historisches Ereignis'), ('creature', 'Kreatur'), ('deity', 'Gottheit'), ('spell', 'Zauber'), ('other', 'Anderes')], help_text='Type of entry', max_length=30)),
                ('summary', models.TextField(blank=True, help_text='Short summary of the entry')),
                ('content', models.TextField(help_text='Main content of the entry')),
                ('image', models.ImageField(blank=True, help_text='Optional image for this entry', null=True, upload_to='wiki/')),
                ('tags', models.CharField(blank=True, help_text='Optional, comma-separated tags for this entry', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0, help_text='How many views this entry has')),
                ('is_published', models.BooleanField(default=True, help_text='Whether this entry is visible to viewers')),
                ('is_spoiler', models.BooleanField(default=False, help_text='Marks this as spoiler and hides it from viewers')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_entries', models.ManyToManyField(blank=True, help_text='Link to other related wiki entries', to='wiki.wikientry')),
                ('system', models.ForeignKey(help_text='Which system this entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='wiki_entries', to='wiki.system')),
            ],
            options={
                'verbose_name': 'Wiki Entry',
                'verbose_name_plural': 'Wiki Entries',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='WikiRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Content at this revision')),
                ('summary', models.TextField(blank=True, help_text='Short summary at this revision')),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('edit_summary', models.CharField(blank=True, help_text='Brief description on made changes', max_length=200)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='wiki.wikientry')),
            ],
            options={
                'verbose_name': 'Wiki Revision',
                'verbose_name_plural': 'Wiki Revisions',
                'ordering': ['-edited_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wikientry',
            index=models.Index(fields=['system', 'entry_type'], name='wiki_wikien_system__87d057_idx'),
        ),
        migrations.AddIndex(
            model_name='wikientry',
            index=models.Index(fields=['title'], name='wiki_wikien_title_3a0b62_idx'),
        ),
        migrations.AddIndex(
            model_name='wikientry',
            index=models.Index(fields=['slug'], name='wiki_wikien_slug_ba4630_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wikientry',
            unique_together={('system', 'slug')},
        ),
    ]
