# Generated by Django 6.0.1 on 2026-02-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikientry',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for this entry', null=True, upload_to='wiki/images'),
        ),
    ]
