context = {
    'stylesheet': 'css/alien.css',
    'campaign_cards': 'alien/campaign_cards.html',
    'characters': 'alien/charaktere.html',
    'campaign': 'alien/kampagnen.html',
    'lore': 'alien/lore.html',
    'sessions': 'alien/sessions.html',
    'site_title': 'Alien',
    'title': 'Alien',
    'subtitle': "Im Weltraum hört dich niemand schreien",
    'welcome': 'In der unendlichen Leere des Alls ist das Überleben kein Sieg, sondern nur ein Aufschub.',
    'quote': [
        '"Im Weltraum hört dich niemand schreien"',
        '"Ich kann dir nichts über deine Chancen vormachen, aber... du hast mein Mitgefühl." - Ash',
        '"Ich werde diesen Ort bis auf die Grundmauern niederbrennen." - Ripley',
        '"Das Schiff wird in fünf Minuten automatisch zerstört." - MU/TH/UR',
        '"Schluss mit dem Unsinn! Hören Sie auf! Kane ist in Quarantäne und dabei bleibts!" - Dallas',
        '"Ich bewundere die konzeptionelle Reinheit. Geschaffen, um zu überleben. '
        'Kein Gewissen beeinflusst es. Es kennt keine Schuld, oder Wahnvorstellungen ethischer Art." - Ash',
        '"Ash ist ein Roboter! Ash ist ein gottverdammter Roboter!" - Parker',
        '"Ein perfekter Organismus" - Ash',
        '"Ich bin davon überzeugt, es bewegt sich durch die Luftschächte." - Parker',
        '"Sie kennen die Quarantänebestimmungen. 24 Stunden sind Vorschrift." - Ripley',
    ],
    'campaign_subtitle': 'Logbuch der Leere',
    'sessions_subtitle': 'Übertragungssignale',
    'lore_subtitle': 'Archive von Weyland-Yutani',
    'characters_subtitle': 'Manifest der Crew',
    'site_title_campaign': 'Alien - Kampagnen',
    'site_title_sessions': 'Alien - Sessions',
    'site_title_lore': 'Alien - Lore',
    'site_title_characters': 'Alien - Charaktere',
    'system_home': 'Alien Home',
    'url_home': 'alien_home',
    'url_campaign': 'alien_campaign',
    'url_sessions': 'alien_sessions',
    'url_lore': 'alien_lore',
    'url_characters': 'alien_characters',
}
