context = {
    'stylesheet': 'css/vampire.css',
    'campaign_cards': 'vampire/campaign_cards.html',
    'characters': 'vampire/charaktere.html',
    'campaign': 'vampire/kampagnen.html',
    'lore': 'vampire/lore.html',
    'media': 'vampire/medien.html',
    'sessions': 'vampire/sessions.html',
    'search': 'vampire/search.html',
    'site_title': 'Vampire: The Masquerade - Codex Umbrae',
    'title': 'Vampire: The Masquerade',
    'subtitle': "Enter the World of Darkness",
    'welcome': 'Welcome to the shadows, where immortal predators walk among mortals, '
               'bound by ancient traditions and cursed with an insatiable thirst.',
    'quote': '"A Beast I am, lest a Beast I become."',
    'campaign_subtitle': 'Chronicles of darkness',
    'sessions_subtitle': 'Tales from the endless night',
    'lore_subtitle': 'Secrets of the Kindred',
    'characters_subtitle': 'Children of Caine',
    'media_subtitle': 'Images from the shadows',
    'search_subtitle': 'Hunt through the archives',
    'site_title_campaign': 'Vampire - Kampagnen',
    'site_title_sessions': 'Vampire - Sessions',
    'site_title_lore': 'Vampire - Lore',
    'site_title_characters': 'Vampire - Charaktere',
    'site_title_media': 'Vampire - Medien',
    'site_title_search': 'Vampire - Suche',
    'system_home': 'Vampire Home',
    'url_home': 'vampire_home',
    'url_campaign': 'vampire_campaign',
    'url_sessions': 'vampire_sessions',
    'url_lore': 'vampire_lore',
    'url_characters': 'vampire_characters',
    'url_media': 'vampire_media',
    'url_search': 'vampire_search',
}