context = {
    'stylesheet': 'css/vampire.css',
    'campaign_cards': 'vampire/campaign_cards.html',
    'characters': 'vampire/charaktere.html',
    'campaign': 'vampire/kampagnen.html',
    'lore': 'vampire/lore.html',
    'sessions': 'vampire/sessions.html',
    'site_title': 'Vampire: The Masquerade',
    'title': 'Vampire: The Masquerade',
    'subtitle': "Enter the World of Darkness",
    'welcome': 'Welcome to the shadows, where immortal predators walk among mortals, '
               'bound by ancient traditions and cursed with an insatiable thirst.',
    'quote': ['"A Beast I am, lest a Beast I become."',
              '''"Gehe nicht gelassen in die gute Nacht" - Dylan Thomas''',
              '"Wehe dem, der ein Kind kränkt" - Fjodor Dostojewski',
              '"Es irrt der Mensch, solang er strebt" - Johann Wolfgang von Goethe',
              '"Alle glücklichen Familien ähneln einander, jede unglückliche Familie ist unglücklich auf ihre eigene '
              'Weise" - Leo Tolstoi',
              '"Tränen reinigen das Herz" - Fjodor Dostojewski',
              '"Die Sehnsucht lässt alle Dinge blügen" - Marcel Proust',
              '"Das einzige Paradies ist das Verlorene" - Marcel Proust',
              '"Das Leben ist zu wichtig, um es ernst zu nehmen" - Oscar Wilde',
              '"Eine schöne Seele adelt den Leib" - Seneca',
              '"Der große Tod, den jeder in sich hat, das ist die Furcht um die sich alles dreht" - '
              'Rainer Maria Rilke',
              '"Du kannst gar nichts tun, weshalb ich aufhören würde dich zu lieben" - Fjodor Dostojewski',
              '"Die Grenze ist überschritten, der Spiegel ist zerbrochen, doch es reflektieren die Scherben" - '
              'Edgar Allan Poe',
              '"Den lieb ich, der unmögliches begehrt" - Johann Wolfgang von Goethe',
              '"Wo ich lebendiges fand, da fand ich Willen zur Macht" - Friedrich Nietzsche',
              '"Alle politischen Geschäfte laufen darauf hinaus, über andere zu regieren" - Aristoteles',
              '"Gleich ist das Loos des Tapferen und Feigen; beide ernten den Tod" - Homer',
              '"Nicht in der Erkenntnis liegt das Glück, sondern im Erwerben der Erkenntnis" - Edgar Allan Poe',
              '"Wer nicht an Magie glaubt, wird sie niemals entdecken" - Roald Dahl',
              '"Der Mensch ist etwas, das überwunden werden muss" - Friedrich Nietzsche',
              '"Wer nicht mehr liebt und nicht mehr irrt, der lasse sich begraben" - Johann Wolfgang von Goethe',
              '"Was auch immer unsere Seelen sind, seine und meine sind gleich" - Emily Bronte',
              '"Es gibt mehr Schönheit in der Wahrheit, auch wenn sie schrecklich ist" - John Steinbeck',
              '"Am Ende ist alles gut. Wenn es nicht gut ist, dann ist es nicht das Ende" - Oscar Wilde',
              ],
    'campaign_subtitle': 'Chronicles of darkness',
    'sessions_subtitle': 'Tales from the endless night',
    'lore_subtitle': 'Secrets of the Kindred',
    'characters_subtitle': 'Children of Caine',
    'media_subtitle': 'Images from the shadows',
    'search_subtitle': 'Hunt through the archives',
    'site_title_campaign': 'Vampire - Kampagnen',
    'site_title_sessions': 'Vampire - Sessions',
    'site_title_lore': 'Vampire - Lore',
    'site_title_characters': 'Vampire - Charaktere',
    'site_title_media': 'Vampire - Medien',
    'site_title_search': 'Vampire - Suche',
    'system_home': 'Vampire Home',
    'url_home': 'vampire_home',
    'url_campaign': 'vampire_campaign',
    'url_sessions': 'vampire_sessions',
    'url_lore': 'vampire_lore',
    'url_characters': 'vampire_characters',
    'url_media': 'vampire_media',
    'url_search': 'vampire_search',
}