context = {
    'stylesheet': 'css/dnd.css',
    'campaign_cards': 'dnd/campaign_cards.html',
    'characters': 'dnd/charaktere.html',
    'campaign': 'dnd/kampagnen.html',
    'lore': 'dnd/lore.html',
    'media': 'dnd/medien.html',
    'sessions': 'dnd/sessions.html',
    'site_title': 'Dungeons and Dragons',
    'title': 'Dungeons & Dragons',
    'subtitle': "The World's Greatest Roleplaying Game",
    'welcome': 'Gather your party and venture forth into realms of magic, mystery, and endless adventure. '
               'Heroes are forged in the fires of battle and the bonds of friendship.',
    'quote': [
        '"The story is yours to tell."',
        '''"I didn't ask how big the room was..."''',
        '"I have darkvision!"',
        '"Can I seduce the dragon?"',
        '"Do sheep count as difficult terrain?"',
        '"In the deepest dungeon, the smallest light casts the longest shadow"',
        '"Magic is just the universe saying yes to whatever you want"',
        '"You meet in a tavern..."',
        '''"We don't need a plan, we have a barbarian"''',
        '"Every hoard begins with a single piece of copper"',
    ],
    'campaign_subtitle': 'Legendary quests await',
    'sessions_subtitle': 'Tales of valor and glory',
    'lore_subtitle': 'Ancient knowledge',
    'characters_subtitle': 'Heroes of legend',
    'media_subtitle': 'Treasures and artifacts',
    'search_subtitle': 'Explore the archives',
    'site_title_campaign': 'D&D - Kampagnen',
    'site_title_sessions': 'D&D - Sessions',
    'site_title_lore': 'D&D - Lore',
    'site_title_characters': 'D&D - Charaktere',
    'site_title_media': 'D&D - Medien',
    'site_title_search': 'D&D - Suche',
    'system_home': 'D&D Home',
    'url_home': 'dnd_home',
    'url_campaign': 'dnd_campaign',
    'url_sessions': 'dnd_sessions',
    'url_lore': 'dnd_lore',
    'url_characters': 'dnd_characters',
    'url_media': 'dnd_media',
    'url_search': 'dnd_search',
}