context = {
    'stylesheet': 'css/dnd.css',
    'campaign_cards': 'dnd/campaign_cards.html',
    'characters': 'dnd/charaktere.html',
    'campaign': 'dnd/kampagnen.html',
    'lore': 'dnd/lore.html',
    'media': 'dnd/medien.html',
    'sessions': 'dnd/sessions.html',
    'site_title': 'Dungeons and Dragons',
    'title': 'Dungeons & Dragons',
    'subtitle': "Das größte Rollenspiel der Welt!",
    'welcome': 'Versammle deine Gruppe und begib dich auf eine Reise in Reiche voller Magie, '
               'Geheimnisse und endloser Abenteuer. Helden werden im Feuer der Schlacht und durch die Bande '
               'der Freundschaft geschmiedet.',
    'quote': [
        '"Ich habe nicht gefragt, wie groß der Raum ist...“‚‘',
        '"Ich habe Darkvision!“',
        '"Kann ich den Drachen verführen?“',
        '"Zählen Schafe als schwieriges Gelände?“',
        '"Im tiefsten Verlies wirft das kleinste Licht den längsten Schatten“',
        '"Magie ist nur das Universum, das zu allem, was du willst, Ja sagt“',
        '"Ihr trefft euch in einer Taverne...“',
        '"Wir brauchen keinen Plan, wir haben einen Barbaren“',
        '"Jeder Schatz beginnt mit einem einzigen Kupferstück“',
    ],
    'campaign_subtitle': 'Legendäre Abenteuer',
    'sessions_subtitle': 'Geschichten von Tapferkeit und Ruhm',
    'lore_subtitle': 'Uraltes Wissen',
    'characters_subtitle': 'Helden der Legenden',
    'site_title_campaign': 'D&D - Kampagnen',
    'site_title_sessions': 'D&D - Sessions',
    'site_title_lore': 'D&D - Lore',
    'site_title_characters': 'D&D - Charaktere',
    'system_home': 'D&D Home',
    'url_home': 'dnd_home',
    'url_campaign': 'dnd_campaign',
    'url_sessions': 'dnd_sessions',
    'url_lore': 'dnd_lore',
    'url_characters': 'dnd_characters',
}